#这不是你应该看的文件。
*title\结束了。
*mode\msg
*bgm\
*bgs\
*bg\DirtField.png
*fg\DirtCave.png
role\ssr\add
role\bg\add
say\bg
"来到这里，我是为了杀死你的。
如果你没有擅自作出那种事情，雪狼的死或许根本就不存在吧？"
say\ssr
"你是想和我的<言语操纵>对抗？你办得到吗？"
say\bg
"你这是默认自己所做的事情了吗？"
say\ssr
"这你应该责怪世吧？是那家伙操纵了黑暗！
杀死了我的父母！杀死了我们亲爱的雪狼！"
say\bg
"不准用"我们的"来形容雪狼，你不配。"
say\ssr
"看来我们谈不下去了呢。"
say\bg
"是的。"
say\aside
说完，冰棍开始吟唱：
say\bg
"<时间倒流>"
say\aside
时间倒流了，回到了莎瑟瑞正在询问青的时候。
say\bg
"<冰针>"
say\aside
一堆的冰针从莎瑟瑞脚底下伸出，扎中莎瑟瑞，莎瑟瑞吐了一口血。
say\bg
"莎瑟瑞，我们已经在未来谈过了，现在不需要再谈一遍了。"
say\me
"冰棍？"
say\aside
莎瑟瑞和青同时叫出声来。
say\bg
"<冰空光束>"
say\aside
一大波蓝色的光束扫向莎瑟瑞，莎瑟瑞急忙避开。
say\ssr
"够了。"
say\aside
莎瑟瑞撩了撩长发。
say\ssr
"<言语操纵--禁止使用魔法>"
say\bg
"啧。"
say\aside
冰棍啧了一声。
say\bg
"看来这个赌注失败了呢。本以为偷袭可以击败你。"
say\me
"等一下，冰棍，你在说什么？"
say\ssr
"看来你们也是世的同伙吧。"
say\me
"世？"
say\ssr
"<言语操纵--束缚自己的双手>"
say\aside
青的双手突然不听使唤，合在一起然后垂下来。
冰棍则没有反应，毕竟它没有手。
say\ssr
"<言语操纵--跟我来>"
say\aside
说完，莎瑟瑞就向前走去，冰棍和青的脚不听使唤地跟上。
走了很久，终于走到了隧道的尽头。
role\s\add
face\s\ban
那里的墙壁上锁满了铁链。一个男人被锁固定在墙上，看起来昏过去了。
那个男人身穿蓝色的立领衣服和黑色裤子，除此之外没有什么特别的了。
say\bg
"世果然活着啊。"
say\aside
冰棍说。
say\ssr
"那个人。。。就是世？"
say\aside
青想起了黑嘴合照里的那个男人，看来就是眼前的这个男人。
说完，莎瑟瑞从脚边的地板上拿出铁链，把冰棍和青固定在墙上。
say\ssr
"这种铁链是原本行星上的监狱使用的。
可以让你们无法使用魔法。
毕竟我的言语操纵的范围只有3米。
我可没有功夫和你们待在一起。"
"老实待着。"
say\aside
说完，莎瑟瑞走向了世。
say\ssr
"<言语操纵--世，醒过来。>"
say\aside
face\s\angry
世突然睁开了双眼。
say\s
"莎瑟瑞--"
say\aside
世瞪着莎瑟瑞说。
say\s
"你究竟什么时候才愿意听我解释？"
say\aside
世吼了一句，然后看了旁边，发现青和冰棍也在。
say\s
"青。。。你怎么在这里？"
say\me
"世，你认识我？"
say\s
"唔。"
say\aside
世突然止住了声音。
say\ssr
"果然第十七只天使就是你派出去的间谍吧？你害死了枯梦。"
say\s
"关于这个，我正想要和你谈。"
say\ssr
"谈？你害死了这么多人？还想和我谈？？！"
say\aside
莎瑟瑞用魔法具现化了一根冰柱压住世的脖子。
say\ssr
"和我谈？？？！
杀死了我的父母，现在连这些可爱的天使们都不放过！"
say\s
"莎。。。。。你。。。听。。。。。。。
我。。。。。说。。。。。。。。。"
say\aside
世被勒得勉强发出声音。
say\ssr
"你还想说什么啊！！！！！你这个异星人！！！！
之前没有把你杀死就是我的失误！"
say\aside
莎瑟瑞压得更用力了。
say\xx
role\xx\add
face\xx\serious
"莎瑟瑞！"
say\aside
突然有人叫住了莎瑟瑞。
兮兮出现在了隧道里。
say\xx
"看见青不对劲，我也跟了上来。。。
没想到。。。原来。。。是你。。。。。。
如果让黑嘴知道。。。你对得起黑嘴吗？"
say\ssr
"是这个人骗了你们，它操纵了黑暗！"
say\xx
"不是他吧！你不能听他解释一下吗？"
say\ssr
"为什么要听这种人说话？就算只有一秒我也不想和这种人对话！！！"
say\aside
突然，兮兮的眼泪从眼眶里流了出来。
say\xx
"已经死了这么多人了。。。你还不满足吗？"
say\aside
听了这话，莎瑟瑞把冰柱放了下来。
say\xx
"如果你不愿意听世的解释，我就在这里死给你看，
失去了黑嘴，我已经没有必要活着了！"
say\ssr
"你。。。。"
say\aside
莎瑟瑞犹豫了一会儿，然后回过头。
say\ssr
"姑且听你解释。"
say\s
"。。。。。。。来到这个行星后，我粗略了解了行星的历史。
我觉得很奇怪，为什么这个行星没有夜晚。"
say\ssr
"所以你就操纵了黑暗来制造你们行星的夜晚？？？"
say\s
"不是的！你听我说！！！
有光，当然就会有暗。
这个行星的光暗根本就不像我的行星一样平衡。
我们行星的光暗是交替出现的！
所以我打算试一试，说不定突变们也可以恢复。
我发现，我拥有<光影操纵>的能力，
可以自由操作光和暗，所以打算小范围地测试白昼和黑夜！"
say\ssr
"你在说什么。。。"
say\aside
世看起来很激动，双手不停地挣扎着，铁链互相碰撞发出声音。
say\s
"如果成功的话，大家都有可能会恢复！"
say\ssr
"你说的话要我怎么相信？毕竟你不是来自这个星球！"
say\xx
"莎瑟瑞！"
say\aside
兮兮叫出声来。
say\xx
"让他试一试。"
say\ssr
"啧。"
say\aside
face\s\serious
莎瑟瑞啧了一声，解开了冰棍，青和世的铁链。
*bg\GrassMaze.png
*fg\GrassMazefg.png
世伸展了一下双臂，然后神情严肃地走向隧道外。
face\xx\normal
say\s
*play\Heavyrock.mp3
*play\Ice_All_3D.mp3
*play\Laser.mp3
*play\Light_All_3D.mp3
*bgm\OST 29 - Deadlocked.mp3
effect\lightshake
"<光影操纵！>"
say\aside
一个巨大的魔法阵在世的脚底展开，不断地扩大，然后覆盖整个行星。
effect\lightshake
*bg\Meadow.png
*fg\Forest.png
突然，天空上的黑暗逐渐消失，暗之森被光笼罩着。
say\dark
"哦。。。。。。"
say\aside
远方的突变突然发出的声音，他们躺在地上，外观逐渐变得正常。
say\ssr
"这。。。"
say\aside
莎瑟瑞不敢相信眼前所发生的的一切。
effect\lightshake
*bg\DirtField.png
*fg\Forest.png
role\xx\remove
role\s\remove
role\bg\remove
role\ssr\remove
现在，行星有了白昼和黑夜。
突变陆续地恢复了正常。
role\xl\add
say\xl
"噗！噗！噗！！！！！！！"
say\aside
雪狼突然从沙地里钻出来，不停地把嘴里的沙子吐出来。
毕竟黑嘴以为雪狼已经死了，把它埋在了雪原的沙堆里面。
*weather\snowstorm
雪原再次下次了暴风雪。
say\xl
"汪，看来那家伙成功了汪~"
say\aside
雪狼看着被光笼罩的暗之森。
role\xl\remove
effect\lightshake
*bg\Meadow.png
*fg\Town1.png
role\kx1\add
role\fj\add
face\kx1\afraid
此时的<家>则进入了黑夜，浮橘和卡西都开始担忧起来。
这是兮兮使用符文向浮橘和卡西进行了说明。
*bg\garden.jpg
*fg\
role\fj\remove
卡西听了，立刻跑到卡茜的坟墓去，把卡茜和芽子的尸体挖出来。
role\kx2\add
role\yz\add
卡茜和芽子的眉毛抖了抖，然后慢慢张开了双眼。
face\kx1\normal
say\kx1
"卡茜！！！"
say\kx2
"卡西！！！"
say\aside
兄弟拥抱在一起，终于团圆了。
role\yz\remove
role\kx2\remove
role\kx1\remove
*bg\Meadow.png
*fg\Forest.png
role\ssr\add
role\s\add
role\xx\add
role\bg\add
世望着天空。
兮兮，青和冰棍也是。
莎瑟瑞跪倒下来。
say\ssr
"对不起，世，还有大家。。。"
say\aside
兮兮走向了莎瑟瑞。
"啪！"
say\aside
兮兮扇了莎瑟瑞一巴掌。
face\xx\serious
say\xx
"我还是无法原谅你。
但是。你记住了。
如果你用困难，就和我们说。
请你不要擅自作出决定。看看你闹出了多大的闹剧！"
say\aside
莎瑟瑞低下头，眼泪一滴一滴地往下掉。
say\bg
"本来，我和雪狼以为你已经杀死了世，
所以打算杀死你报仇，现在既然人活生生地在这里，
那我也没必要做出那种事情了。"
say\me
"对了，雪狼为什么这么在意世啊。"
say\aside
青发问了。
say\s
"因为世是黑嘴的知音好友，而且雪狼它其实--喜欢黑嘴哦。"
“世也是雪狼的好朋友呢。”
say\me
"可是。。。黑嘴它。。。"
"这么说来，我有一件事没有和大家说明呢。是久悠告诉我的。"
say\s
"等等，在那之前我也说明一件事情吧。"
say\aside
世抢过话题。
say\s
"一开始，我是打算创造青来帮我解决误会的，
结果因为失误，青不能被我操纵，但是我可以看到青在干什么。"
say\me
"等等，我是被你创造的？"
say\s
"是啊。我的魔法<人格创造>。"
say\aside
青突然想起之前提到地球的时候，
有人在和他说话，是的，
那个声音和眼前的世说话的声音一模一样。
say\me
"你为什么在我提到地球的时候就要阻止我呢？"
say\s
"因为我觉得。。。如果你深入地球这件事情，就会被莎瑟瑞盯上啊。"
say\me
"什么鬼。。。"
say\s
"第十七天使也是我创造的。
大家就不用关心它了。
它和青不一样，是我灵力的一部分，不是真实存在的生物。
不过好像我搞砸了。。。。。。"
say\me
"搞砸。。。？"
say\s
"是啊。。。
在枯梦使用<梦境显现>的时候，
我被旁边突然接近的突变杀死了。
看起来对枯梦的打击很大，
枯梦可能以为是它的梦境显现显现出了突变吧。。。
或者说。。。是因为失去我。。。？啊，才不是啦。"
say\me
"所以它才失控了？。。"
say\s
"我想。。。它失控。。。可能是因为。。。"
say\aside
世突然脸红起来。
"。。。"
say\aside
在场的天使都无语了。
say\me
"那么，冰棍你说要解释的事情是什么呢？"
say\aside
青转向冰棍。
say\bg
"嗯，是这样的。
黑嘴不是每次使用圣光种子都会出现一朵金色的小花吗？
其实只要集齐100朵小花，黑嘴的肉体就可以重生了。"
face\xx\afraid
say\xx
"青，第一百朵在哪里？"
say\me
"在。。。黑嘴的床上。"
say\aside
role\xx\remove
说完，兮兮立刻向着家的方向跑去。
没错，每次黑嘴使用圣光种子，
都会把生成的金色小花种植在圣光之泉的洞穴外。
say\s
"大家如果一开始就坦诚相待。。。就没有这么多事情了。"
say\me
"是啊。。。"
go\ending
role\bg\remove
role\s\remove
role\ssr\remove
say\aside
*bg\Wood2.png
*fg\Tent.png
*bgm\OST 1 - Lonely Rainbow.mp3
role\bm\add
role\xx\add
face\xx\love
face\bm\sad
一个月后。
say\xx
"啊呜~"
say\bm
"兮兮。。。你也该学一学煮菜了。。。不能天天来我这里蹭饭啊。"
say\aside
黑嘴一脸鄙视地看着坐在面前的兮兮。
say\xx
"啊呜~有什么关系嘛。"
say\bm
face\bm\normal
"也是。就当做庆祝吧。
行星上的居民都恢复了正常。
据说莎瑟瑞也找到了自己的父母。枯梦也醒过来了。"
say\xx
"哼。那家伙，现在整天和世在一起。看来他们的误会也已经解决了。"
say\bm
"是啊。。。
我都没什么机会和我亲爱的知音好友世说话了呢。
说起来，原来枯梦并没有想象中的那么坏啊。
原来它有着那样的过去。"
say\xx
"哈哈。
啊呜~现在这个行星已经开始重新建筑了，
不久过后附近就会热闹起来吧。"
say\bm
face\bm\sad
"是啊。。。可惜。。。。只有老师不在了。"
say\xx
face\xx\sad
"哎。。。"
say\aside
兮兮望了一眼窗外。窗外的后院上建着久悠的坟墓，上面放满了鲜花。
say\xx
*bgm\OST 3 - Sweet Flower.mp3
"不过。。。
据说原本行星上的居民拥有复活魔法，说不定再过不久，
久悠还能醒过来呢。"
say\aside
兮兮安慰黑嘴说。
say\bm
face\bm\normal
face\xx\love
"突变这个病症也有了一些可靠的数据。
突变将病毒藏在自己的魔法里面，通过使用魔法攻击其他人来传染病毒。。。
被传染的人会出现一段时间的假死状态。。。
随后就会变成突变。"
say\xx
"是啊。。。我们还把雪狼给埋在沙地里了。。。"
say\bm
"哈哈。。。我也不知道嘛。"
say\xx
"我还记得它回到<家>的时候的表情，噗哈哈。
不过大家还在，这就是最好的事情了。"
say\aside
*bgm\OST 15 - Milk Tea.mp3
"黑嘴！"
say\aside
role\xl\add
role\bg\add
role\qing\add
这时，雪狼和青破门而入。冰棍则站在雪狼的头上。
say\qing
"这么好吃的饭菜怎么可以不邀请我们！"
say\bm
"啊。。。？"
say\xx
"是我叫他们来的哦。"
say\aside
兮兮得意地摇了摇汤勺。
say\bm
"啊。你早说啊。"
say\aside
role\qing\remove
role\bg\remove
role\xl\remove
role\xx\remove
role\bm\remove
role\s\add
role\km1\add
说完，世和枯梦也进来了。
say\s
"那干脆大家一起开个派对庆祝吧。"
role\km1\remove
role\s\remove
role\xl\add
role\bg\add
role\qing\add
say\aside
face\xl\happy
"好哇！"
say\aside
青和雪狼叫道。
role\qing\remove
role\bg\remove
role\xl\remove
role\xx\add
role\s\add
face\xx\love
say\xx
"OK！"
say\aside
兮兮举着汤勺和世说。
say\s
"Well , let's go !"
say\aside
世也用英语和兮兮对话。
role\s\remove
role\xx\remove
*bg\garden.jpg
*fg\Port.png
大家都走出了门，兮兮也赶忙拿起碗走出去，一边走一边吃。
role\yy\add
role\tk\add
*bgm\OST 24 - Across The Waters.mp3
雅月早已在<家>的草地上开起了舞会，
一旁的塔克在挥舞着镰刀，可能是在跳舞吧。
role\xl\add
role\bg\add
role\qing\add
face\xl\happy
雪狼，冰棍和青也跟着一起跳起舞来。
世搭上黑嘴的肩膀，世牵着枯梦的手，
而黑嘴牵着兮兮的手，在草地上坐下来。
role\qing\remove
role\bg\remove
role\xl\remove
role\tk\remove
role\yy\remove
role\s\add
role\bm\add
say\bm
"好久没有这样了呢。"
say\aside
黑嘴和世说。
say\s
"是啊。。。没有告诉你圣光种子的真相，真的很抱歉。"
say\bm
"没关系。。。只要你还在就好。
不过你没有交代重生肉体的时候没穿衣服啊！"
say\s
"。。。这是我谋划给兮兮的福利。"
*bgm\OST 10 - Sweet Candy.mp3
say\aside
role\xx\add
face\xx\slove
face\bm\slove
"才不要！"
say\aside
黑嘴和兮兮同时向世吼。
role\bm\remove
role\xx\remove
role\km1\add
say\km1
"世。"
say\aside
枯梦靠着世的肩膀。
say\km1
"终于见到你了。。。太好了。。。我们下次再玩拼图吧。"
say\s
"好哇。"
say\aside
这时，卡西和卡茜也过来了。
芽子突然从地底钻出来捂住黑嘴的脸，说：
"黑嘴酱~我来~喽~"
"呀~你放开啦。"
say\aside
兮兮把芽子推开。
"哈哈哈。"
say\aside
芽子笑了一声，用奇特的步子加入了跳舞的行列。
莎瑟瑞也和他的父母过来了，浮橘则高速旋转着叶片，飞到黑嘴的头顶上。
还有一只天使飞了过来，它像是一只白色幽灵，头上戴着魔术帽。
"迪娜！"
say\aside
黑嘴叫出了它的名字。
"啊。。。睡了好久，发生了什么？"
"啊，你真是的。"
say\aside
黑嘴无奈地笑了笑。
迪娜大部分时间都在睡觉，甚至不知道发生了什么大事。
"我有个提议。"
say\aside
世说。
"我们来一张合照吧。"
"赞成~"
say\aside
在场的所有天使一齐答应道。
此时久悠的坟墓上，燃起了一丝火花。
say\aside
圣光滋润的行星，被树林包围着，曾经寂静的大地，现在渐渐恢复了生机。
go\ending
