#这不是你应该看的文件。
*title\冰河风暴
*mode\msg
*bgm\
*bgs\
*bg\Wood2.png
*fg\Stone2.png
*weather\
role\xl\add
role\bg\add
role\bm\add
role\xx\add
say\aside
face\xl\serious
face\bm\afraid
face\xx\afraid
"。。。"
所有天使陷入了沉思。
究竟是什么天使，基于什么目的带走了第十七只天使。
然而，令人毛骨悚然的是黑嘴接下来说的话。
"为了调查它的下落。。。。我拜访了所有天使一遍。
say\bm
但唯独联系不上枯梦。
say\aside
"枯梦。。。。"
所有天使的表情露出一丝愤怒的神色。
枯梦，全天使公认的最没有道德、最狠毒、最讨人厌的天使。
不难想象枯梦会做出什么出格的事。
say\bm
"我现在必须前往预言师那里。
它可以预测到天使接下来的动向。”
黑嘴整了整领带。
"不过。。。预言师却指定要青也一起来。。。
它说预测第十七只天使的动向需要青的力量。"
"呼。。。"
face\bm\sad
黑嘴吐了一口气。
"青。。。你愿意帮助我们吗？"
say\me
"当然了！"
face\bm\normal
face\xx\normal
face\xl\normal
青十分严肃地大声回答。在场的天使都微笑起来。
say\bm
"那么。"
黑嘴转向雪狼。
"你得先突破眼前这道关卡呢。"
say\xl
"汪~"
雪狼闭上眼，竖起双耳。
"冰河风暴！！！！！！！！！！！！！"
雪狼大声吟唱出来。
say\aside
*bgs\Wind_1_3D_loop.mp3
*bg\Snowfield.png
*fg\Sky.png
*weather\snowstorm
role\bg\remove
role\bm\remove
role\xx\remove
空间突然下起了猛烈的暴风雪，以雪狼为中心展开了一片雪地，
雪地所到之处都化为了一片虚无。
暴风雪中的雪地上，只留下青和雪狼两人。
青不由得四处张望。
say\xl
"这是我的特殊能力一一冰河风暴。
可以随意地将天使移动到自己的精神世界中。
嘛。
暴风雪也是特性之一。
也就是说。
这里是我的世界，一切的法则由我来决定，不过，
我不会做出什么奇怪的法则，只是希望我们的战斗不要干扰到外界罢了。
与其说是精神世界，不如说是一个完全由我掌控的世界。
你的肉体也活生生地在这里。
这意味着，你。。。"。
face\xl\serious
雪狼的表情变得无情，冷酷。
"可能会死在这里。"
暴风吹拂而过。
go\snowstorm

